# Generated by Django 3.2.5 on 2022-02-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviemodel',
            name='poster_image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
